# checks all runtimes we care about (kusama, polkadot, westend) and ensures
# the bootnodes in their respective chainspecs are contactable

name: Check all bootnodes
on: push

jobs:
  check_bootnodes:
    strategy:
      fail-fast: false
      matrix:
        runtime: [westend, kusama, polkadot]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install polkadot
        shell: bash
        run: |
          curl -L "$(curl -s https://api.github.com/repos/paritytech/polkadot/releases/latest \
          | jq -r '.assets | .[] | select(.name == "polkadot").browser_download_url')" \
          | sudo tee /usr/local/bin/polkadot > /dev/null
          sudo chmod +x /usr/local/bin/polkadot
          polkadot --version
      - name: Check ${{ matrix.runtime }} bootnodes
        shell: bash
        run: scripts/ci/github/check_bootnodes.sh ${{ matrix.runtime }}